export const projects = [
  {
    id: "task-flow",
    title: "WorkFlow Platform",
    subtitle: "Real-Time Task Management & Team Collaboration Platform",
    description:
      "A real-time task management and team collaboration platform built to help teams organize workspaces, manage visual boards, collaborate on tasks, and track workflow updates.",
    features: [
      "Workspace and board management",
      "Kanban-style task boards",
      "Drag-and-drop task cards",
      "Real-time board updates",
      "Member roles and permissions",
      "Comments and activity tracking",
      "Labels, due dates, reminders, and checklists",
      "File attachments and image optimization",
      "Email and desktop notifications"
    ],
    caseStudy: {
      overview: "WorkFlow Platform is a private company project designed for workspace-based task management. It allows users to create boards, manage task lists, move cards, assign members, add comments, upload attachments, set reminders, and receive real-time activity updates.",
      role: "I worked as a Software Developer on both frontend and backend workflows. My contributions included board interactions, API integration, authentication handling, real-time updates, reusable UI components, file upload workflows, and production issue fixes.",
      technicalHighlights: [
        "Built frontend modules using React 19, TypeScript, Vite, TanStack Router, and TanStack Query",
        "Integrated real-time updates using Socket.io",
        "Implemented drag-and-drop board interactions",
        "Built backend APIs using Node.js, Express.js, MongoDB, and Mongoose",
        "Worked with JWT authentication and protected routes",
        "Used React Hook Form and Zod for form validation",
        "Handled file uploads using Multer and image optimization using Sharp",
        "Supported testing with Jest, Vitest, React Testing Library, and Supertest"
      ],
      challengeSolution: "The main challenge was keeping boards, lists, cards, comments, members, and notifications synchronized when multiple users interacted with the same workspace.\n\nI worked with structured REST API integration, Socket.io events, TanStack Query cache handling, and reusable board components to keep the interface responsive and consistent.",
      confidentialityNote: "This is a private company project. The project name, screenshot, branding, and selected details have been generalized for portfolio-safe presentation. Source code, live access, internal URLs, client data, and business-sensitive information are not publicly shared."
    },
    image: "/images/task-flow/task-flow-thumbnail.png",
    sliderImages: [
      "/images/task-flow/task-flow-thumbnail.png",
      "/images/task-flow/task-flow-thumbnail.png",
      "/images/task-flow/task-flow-thumbnail.png",
    ],
    tags: [
      "React 19",
      "TypeScript",
      "Vite",
      "TanStack Router",
      "TanStack Query",
      "Tailwind CSS",
      "Socket.io",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Mongoose",
      "JWT",
      "Zod",
      "Multer",
      "Sharp",
      "Jest",
      "Vitest",
      "React Testing Library"
    ],
    isPrivate: true,
    liveUrl: "#",
    githubUrl: "#",
    className: "md:col-span-1",
  },
  {
    id: "cloud-secure",
    title: "Secure Access Platform",
    subtitle: "Secure Project Access & Credential Management Platform",
    description:
      "A secure project access and credential management platform built to protect project-related data using multi-factor authentication, role-based access control, encrypted custom fields, and secure file handling.",
    features: [
      "Email-based authentication flow",
      "TOTP authenticator setup using QR code",
      "Secure login with 6-digit authenticator code",
      "Access and refresh token handling",
      "Protected routes",
      "Project creation and management",
      "Project member management",
      "Owner, editor, and viewer role permissions",
      "Custom text and file fields",
      "Encrypted text field storage",
      "Encrypted file upload and download",
      "Superadmin user management",
      "User activation and deactivation",
      "Project ownership transfer",
      "Search, pagination, and data tables"
    ],
    caseStudy: {
      overview: "Secure Access Platform is a private company project designed for managing secure projects, users, project members, roles, custom fields, and encrypted project-related information. The platform allows authenticated users to create projects, manage members, store sensitive text fields, upload protected files, and control access based on user roles.",
      role: "I worked as a Software Developer on both frontend and backend workflows. My contributions included authentication screens, TOTP verification flow, protected routes, project management workflows, member role handling, secure API integration, reusable UI components, form validation, and production issue fixes.",
      technicalHighlights: [
        "Built frontend modules using React 19, TypeScript, Vite, TanStack Router, and TanStack Query",
        "Used TanStack Table for project and user management tables",
        "Integrated protected REST APIs using Axios",
        "Built authentication steps for email entry, QR setup, and TOTP verification",
        "Used React Hook Form and Zod for form validation",
        "Implemented protected frontend routes and superadmin-only routes",
        "Built backend APIs using Node.js, Express.js, TypeScript, and MySQL/MariaDB",
        "Implemented JWT-based access token and refresh token authentication",
        "Used HTTP-only refresh token cookies for safer session handling",
        "Implemented role-based access control for project owners, editors, and viewers",
        "Used AES-256-GCM encryption for sensitive text and file data",
        "Handled file uploads using Multer",
        "Used Helmet, CORS, cookie-parser, and centralized error handling",
        "Added project member controls including role update, member removal, and ownership transfer"
      ],
      challengeSolution: "The main challenge was protecting sensitive project information while keeping project collaboration simple for users.\n\nI worked with multi-factor authentication, protected routes, JWT session handling, role-based access control, encrypted custom fields, and structured API integration to keep the platform secure, usable, and maintainable.",
      confidentialityNote: "This is a private company project. The project name, screenshot, branding, and selected details have been generalized for portfolio-safe presentation. Source code, live access, internal URLs, user data, project records, and business-sensitive information are not publicly shared."
    },
    image: "/images/cloude-secure/cloud-secure-thumbnail.png",
    sliderImages: [
      "/images/cloude-secure/cloud-secure-thumbnail.png",
      "/images/cloude-secure/cloud-secure-thumbnail.png",
      "/images/cloude-secure/cloud-secure-thumbnail.png",
    ],
    tags: [
      "React 19",
      "TypeScript",
      "Vite",
      "TanStack Router",
      "TanStack Query",
      "TanStack Table",
      "Tailwind CSS",
      "Radix UI",
      "React Hook Form",
      "Zod",
      "Axios",
      "Node.js",
      "Express.js",
      "MySQL",
      "MariaDB",
      "JWT",
      "TOTP",
      "QR Code",
      "Multer",
      "AES-256-GCM",
      "Helmet"
    ],
    isPrivate: true,
    liveUrl: "#",
    githubUrl: "#",
    className: "md:col-span-1",
  },
  {
    id: "cleanerz",
    title: "Cleanerz",
    subtitle: "Service Marketplace & Booking Management Platform",
    description:
      "A service marketplace and booking management platform built to connect customers with service providers through booking, scheduling, provider management, admin operations, and service tracking workflows.",
    features: [
      "Consumer and provider management",
      "Booking management",
      "Provider verification and status handling",
      "Help support management for consumers and providers",
      "Product, brand, vendor, category, and attribute management",
      "E-commerce order management",
      "Pricing packages and service management",
      "Bonus slot management",
      "Promo code management",
      "Admin user management",
      "Roles and permissions",
      "Search, pagination, filters, and data tables",
      "Image upload and file handling workflows"
    ],
    caseStudy: {
      overview: "Cleanerz is a service marketplace platform designed to manage cleaning service operations across customers, providers, vendors, bookings, support requests, pricing, promo codes, and e-commerce workflows. The platform includes an admin dashboard for managing users, bookings, services, providers, products, orders, and operational settings from a centralized interface.",
      role: "I worked as a Software Developer on the admin dashboard and API-connected platform workflows. My contributions included building dashboard modules, integrating REST APIs, handling booking and user management flows, creating reusable table and modal components, managing form workflows, implementing role-based access handling, and improving admin-side usability.",
      technicalHighlights: [
        "Built dashboard modules using React 19, Vite, and CoreUI",
        "Integrated REST APIs using Axios",
        "Used TanStack Query for API state management",
        "Built reusable table, modal, header, and form components",
        "Implemented routing using React Router",
        "Used React Hook Form for form workflows",
        "Used React Select for dropdown and selection-based inputs",
        "Implemented pagination using React Paginate",
        "Handled image uploads using React Dropzone and image upload utilities",
        "Used Redux for application-level state handling",
        "Built role and permission based UI access handling",
        "Created structured modules for user management, booking management, help support, e-commerce, pricing, promo codes, and admin settings"
      ],
      challengeSolution: "The main challenge was managing multiple operational modules in one admin dashboard while keeping the interface simple, consistent, and easy to maintain.\n\nI worked with reusable components, structured feature-based modules, API hooks, table utilities, pagination, form handling, and role-based access logic to keep the dashboard scalable and easier to manage.",
    },
    image: "/images/cleanerz/cleanerz-thumbnail.png",
    sliderImages: [
      "/images/cleanerz/cleanerz-thumbnail.png",
      "/images/cleanerz/cleanerz-thumbnail.png",
      "/images/cleanerz/cleanerz-thumbnail.png",
    ],
    tags: [
      "React 19",
      "Vite",
      "JavaScript",
      "CoreUI",
      "TanStack Query",
      "React Router",
      "Redux",
      "Axios",
      "React Hook Form",
      "React Select",
      "React Paginate",
      "React Dropzone",
      "Chart.js",
      "Sass"
    ],
    isPrivate: false,
    liveUrl: "https://cleanerzapp.com/",
    githubUrl: "#",
    className: "md:col-span-1",
  },
];
